import sqlite3
import os
import tqdm

def create_table(c,S_code):
	S_code = S_code.replace('.','_')
	S_code = S_code.lower()
	COMMAND = "CREATE TABLE IF NOT EXISTS {} (IDX INTEGER PRIMARY KEY, DATE INTEGER, OPEN REAL, HIGH REAL, LOW REAL, CLOSE REAL, VOLUME INTEGER, RATE REAL, BBANDSU REAL, BBANDSM REAL, BBANDSL REAL, KAMA REAL, MA REAL, MAMA REAL, FAMA REAL, MIDPOINT REAL, MIDPRICE REAL, SMA REAL, T3 REAL, TRIMA REAL, WMA REAL, ADX REAL, ADXR REAL, APO REAL, ARROND REAL, ARRONU REAL, ARRONOSC REAL, BOP REAL, CCI REAL, CMO REAL, DX REAL, MACD REAL, MACDS REAL, MACDH REAL, MACDEXT REAL, MACDEXTS REAL, MACDEXTH REAL, MACDFIX REAL, MACDFIXS REAL, MACDFIXH REAL, MFI REAL, MINUSDI REAL, MINUSDM REAL, MOM REAL, PLUSDI REAL, PLUSDM REAL, PPO REAL, ROC REAL, ROCP REAL, ROCR REAL, ROCR100 REAL, RSI REAL, STOCHK REAL, STOCHD REAL, STOCHJ REAL, STOCHFK REAL, STOCHFD REAL, STOCHRSIK REAL, STOCHRSID REAL, TRIX REAL, ULTOSC REAL, WILLR REAL, AD REAL, ADOSC REAL, OBV REAL, ATR REAL, NATR REAL, TRANGE REAL, CDL2CROWS REAL, CDL3BLACKCROWS REAL, CDL3INSIDE REAL, CDL3LINESTRIKE REAL, CDL3OUTSIDE REAL, CDL3STARSINSOUTH REAL, CDL3WHITESOLDIERS REAL, CDLABANDONEDBABY REAL, CDLADVANCEBLOCK REAL, CDLBELTHOLD REAL, CDLBREAKAWAY REAL, CDLCLOSINGMARUBOZU REAL, CDLCONCEALBABYSWALL REAL, CDLCOUNTERATTACK REAL, CDLDARKCLOUDCOVER REAL, CDLDOJI REAL, CDLDOJISTAR REAL, CDLDRAGONFLYDOJI REAL, CDLENGULFING REAL, CDLEVENINGDOJISTAR REAL, CDLEVENINGSTAR REAL, CDLGAPSIDESIDEWHITE REAL, CDLGRAVESTONEDOJI REAL, CDLHAMMER REAL, CDLHANGINGMAN REAL, CDLHARAMI REAL, CDLHARAMICROSS REAL, CDLHIGHWAVE REAL, CDLHIKKAKE REAL, CDLHIKKAKEMOD REAL, CDLHOMINGPIGEON REAL, CDLIDENTICAL3CROWS REAL, CDLINNECK REAL, CDLINVERTEDHAMMER REAL, CDLKICKING REAL, CDLKICKINGBYLENGTH REAL, CDLLADDERBOTTOM REAL, CDLLONGLEGGEDDOJI REAL, CDLLONGLINE REAL, CDLMARUBOZU REAL, CDLMATCHINGLOW REAL, CDLMATHOLD REAL, CDLMORNINGDOJISTAR REAL, CDLMORNINGSTAR REAL, CDLONNECK REAL, CDLPIERCING REAL, CDLRICKSHAWMAN REAL, CDLRISEFALL3METHODS REAL, CDLSEPARATINGLINES REAL, CDLSHOOTINGSTAR REAL, CDLSHORTLINE REAL, CDLSPINNINGTOP REAL, CDLSTALLEDPATTERN REAL, CDLSTICKSANDWICH REAL, CDLTAKURI REAL, CDLTASUKIGAP REAL, CDLTHRUSTING REAL, CDLTRISTAR REAL, CDLUNIQUE3RIVER REAL, CDLUPSIDEGAP2CROWS REAL, CDLXSIDEGAP3METHOD REAL, BETA REAL, CORREL REAL, LINEARREG REAL, LINEARREGANGLE REAL, LINEARREGINTERCEPT REAL, LINEARREGSLOPE REAL, STDDEV REAL, TSF REAL, VAR REAL)".format(S_code)
	try:
		c.execute(COMMAND)
	except sqlite3.OperationalError and sqlite3.DatabaseError:
		pass
		pass



def main():
	connection = sqlite3.connect("{}.db".format('Stock'))
	c = connection.cursor()
	files = os.listdir(os.getcwd()+'/Stock_data')
	for i in tqdm.tqdm(range(len(files))):
		file = files[i]
		file_name = file[:-4]
		create_table(c, file_name)
	connection.commit()

if __name__ == '__main__':
	main()
